# Generated by Django 6.0.5 on 2026-05-30 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowed_books', '0001_initial'),
        ('returned_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('copies_lent', models.PositiveIntegerField(default=1)),
                ('date_borrowed', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lending_records', to='borrowed_books.book')),
            ],
            options={
                'ordering': ['-date_borrowed'],
            },
        ),
    ]
